### ISSUE TITLE
welcome to bottle bits issues

### ISSUE THREAD

**Issue by snehaajency** [ajency/bottlebits#15]
**case**:
1. "next" font family is wrong,should be Nunito Sans ExtraBold
2.width of button is small in web.
3.the second line is not according to design, should be "Your journey to investing, collecting, and connoisseurship starts here…"
4.close icon is missing.
5."for now,just relax,we will give...." line the word "just" should be bold.
6.font size for text is more,should be 18px.
7.secon paragrapgh," a journey of.." word should be bold.
8.3 dots are appearing for welcome page also (https://bottlebits.thotakaa.com/#)
web:
![image](https://user-images.githubusercontent.com/4660706/110627098-8ed91b00-81c7-11eb-854c-051a49682308.png)
![image](https://user-images.githubusercontent.com/4660706/110627567-276f9b00-81c8-11eb-8fce-2b223742b19f.png)

design:
![image](https://user-images.githubusercontent.com/4660706/110627384-eaa3a400-81c7-11eb-9244-45f1034364cf.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency 2,5,6,7
on safari:the structure is breaking.

**Comment by chaitanya-ajency** [comment]
on safari:the structure is breaking: issue pending

**Comment by snehaajency** [comment]
fixed
