### ISSUE TITLE
question-2 issues.

### ISSUE THREAD

**Issue by snehaajency** [ajency/bottlebits#16]
**case**:font family should be "New York Regular" for "To understand your preferences, take a short survey"
2.font family for next button :Nunito Sans ExtraBold
3."of 3" is missing below the question number.
4.font family for options provided is New York Regular
5.font size for "previous" is 14px
6.3 vertical dots on right missing

design:
![image](https://user-images.githubusercontent.com/4660706/110629976-d2815400-81ca-11eb-81b4-87df5228aca0.png)
web:
![image](https://user-images.githubusercontent.com/4660706/110630019-ddd47f80-81ca-11eb-89ce-5d7ff5e23b7d.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency 2,3,5 not fixed

**Comment by snehaajency** [comment]
@chaitanya-ajency 
the options width is not proper
![image](https://user-images.githubusercontent.com/4660706/110776324-f2c21900-8285-11eb-9624-d7c85e50b11a.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency :1.of 3, font fam:New York Regular Italic
2.5th point not fixed.
3.width of options is not fixed.
4.check the back arrow thickness

**Comment by chaitanya-ajency** [comment]
@hazel @sneha 1. could'nt find font family itallic
4. back icon not found
