### ISSUE TITLE
question-1 issues

### ISSUE THREAD

**Issue by snehaajency** [ajency/bottlebits#22]
1."of 3" missing.
2.cross icon missing
3.ui breaking on mobile

![image](https://user-images.githubusercontent.com/4660706/110750571-b3390400-8268-11eb-8542-20d97c535e6b.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency above issues are fixed

font family doesnot look correct through:
![image](https://user-images.githubusercontent.com/4660706/110932928-1c487680-8352-11eb-9402-4ce61958cf51.png)

**Comment by chaitanya-ajency** [comment]
Could'nt find new york bold
